// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vorqwgmnfgjbjcuiaqkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvcnF3Z21uZmdqYmpjdWlhcWtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MDU2NjgsImV4cCI6MjA2MzM4MTY2OH0.Xp-phBxKrEZ0CYhRu_-KmBmqftU7_DoWJq14WZyQXtU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);